# ----------------------------------------------------------------------------------------
# Docker image for populating deployment-data volume with project specific customisations
# ----------------------------------------------------------------------------------------
FROM alpine:latest

RUN mkdir -p /deployment-source/manager/extensions
ADD image /deployment-source
